### ISSUE TITLE
touch only working in one screen orientation

### ISSUE THREAD

**Issue by sigboe** [onitake/gsl-firmware#4]
I build the firmware with

    ./fwtool -c SileadTouch.fw -3 -m 1680 -w 1700 -h 1125 -t 10 -f track,yflip silead_ts.fw

And it only tracks correctly in the clockwise screen rotation. I don't know how X work, but I don't see why this should be an issue. Is there a workaround? If rotation worked, then there would be point in trying to get the accelerometer to work as well.

**Comment by onitake** [comment]
I don't quite understand what your issue is.
As far as the driver is concerned, once the touch event is out, it's the userspace application's job to handle any mapping to the output device. The xflip and yflip flags are merely there so the "natural" direction of the axes can be restored.

How exactly is tracking not working in different screen orientations? What are you trying to do, and what is the result?

**Comment by onitake** [comment]
I'm closing this issue now.
Feel free to reopen (or create a new issue) if you have further input.
